<?xml version = "1.0"?>
<project name="MyInfArithProject" default="compile" basedir=".">

    <property name="src.dir"     value="arbitraryarithmetic"/>
    <property name="build.dir"   value="build"/>
    <property name="main.class"  value="MyInfArith"/>


    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

   
    <target name="init">
        <mkdir dir="${build.dir}"/>
    </target>


    <target name="compile" depends="init">
        <javac destdir="${build.dir}" includeantruntime="false">
        <src path = "arbitraryarithmetic"/>
        <src path = "."/>
        </javac>
    </target>

    <target name="jar" depends="compile">
        <jar destfile="MyInfArith.jar" basedir="${build.dir}">
            <manifest>
                <attribute name="Main-Class" value="${main.class}"/>
            </manifest>
        </jar>
    </target>

</project>
